export const songdata = [
  {
    id: 1,
    artist: "Ying Yang Twins",
    title: "I Yi Yi",
    key: 2,
    bpm: 94,
  },
  {
    id: 2,
    artist: "2Pac",
    title: "How Do U Want It",
    key: 2,
    bpm: 94,
  },
  {
    id: 3,
    artist: "Too Short",
    title: "Couldn't Be a Better Player",
    key: 2,
    bpm: 94,
  },
  {
    id: 4,
    artist: "Snoop Dogg",
    title: "What's My Name",
    key: 10,
    bpm: 94,
  },
  {
    id: 5,
    artist: "Notorious BIG",
    title: "Hypnotize",
    key: 9,
    bpm: 94,
  },
  {
    id: 6,
    artist: "Nas",
    title: "If I Ruled the World",
    key: 2,
    bpm: 94,
  },
  {
    id: 7,
    artist: "Mobb Deep",
    title: "Shook Ones Part 2",
    key: 3,
    bpm: 94,
  },
  {
    id: 8,
    artist: "Ludacris",
    title: "Southern Hospitality",
    key: 10,
    bpm: 94,
  },
  {
    id: 9,
    artist: "Lil Wayne",
    title: "Shine",
    key: 6,
    bpm: 94,
  },
  {
    id: 10,
    artist: "Kane and Abel",
    title: "Show Dat Work",
    key: 8,
    bpm: 94,
  },
  {
    id: 11,
    artist: "Juvenile",
    title: "Back Dat Ass Up",
    key: 7,
    bpm: 94,
  },
  {
    id: 12,
    artist: "J-Kwon",
    title: "Tipsy",
    key: 4,
    bpm: 94,
  },
  {
    id: 13,
    artist: "Dr Dre",
    title: "The Next Episode",
    key: 2,
    bpm: 94,
  },
  {
    id: 14,
    artist: "David Banner",
    title: "Play",
    key: 5,
    bpm: 94,
  },
  {
    id: 15,
    artist: "Clipse",
    title: "Grindin'",
    key: 4,
    bpm: 94,
  },
  {
    id: 16,
    artist: "Ali",
    title: "Breathe In, Breathe Out",
    key: 8,
    bpm: 94,
  },
  {
    id: 17,
    artist: "C-Murder",
    title: "Down for my Ns",
    key: 1,
    bpm: 94,
  },
  {
    id: 18,
    artist: "Boo & Gotti",
    title: "Ain't It Man",
    key: 4,
    bpm: 94,
  },
  {
    id: 19,
    artist: "T.I.",
    title: "Why U Wanna",
    key: 8,
    bpm: 94,
  },
  {
    id: 20,
    artist: "50 Cent",
    title: "In Da Club",
    key: 6,
    bpm: 94,
  },
  {
    id: 21,
    artist: "Beyonce",
    title: "Single Ladies",
    key: 4,
    bpm: 94,
  },
  {
    id: 22,
    artist: "50 Cent",
    title: "I Get It In",
    key: 12,
    bpm: 94,
  },
  /*{
    id: 23,
    artist: "Dr. Dre",
    title: "G Thang",
    key: 11,
    bpm: 94
}, */ {
    id: 24,
    artist: "Lil Mo",
    title: "Superwoman Remix",
    key: 12,
    bpm: 94,
  },
  {
    id: 25,
    artist: "Fabolous",
    title: "Can't Deny It",
    key: 4,
    bpm: 94,
  },
  {
    id: 26,
    artist: "Masta Ace",
    title: "Born to Roll",
    key: 4,
    bpm: 94,
  },
  {
    id: 29,
    artist: "Ludacris",
    title: "Ho",
    key: 8,
    bpm: 94,
  },
  {
    id: 30,
    artist: "Snoop Dogg",
    title: "Deep Cover",
    key: 4,
    bpm: 94,
  },
  {
    id: 31,
    artist: "Snoop Dogg",
    title: "Drop It Like Its Hot",
    key: 9,
    bpm: 94,
  },
  {
    id: 32,
    artist: "Dr Dre",
    title: "Dre Day",
    key: 1,
    bpm: 94,
  },
  {
    id: 34,
    artist: "Juvenile",
    title: "Ha",
    key: 5,
    bpm: 94,
  },
  {
    id: 35,
    artist: "Silk the Shocker",
    title: "Aint My Fault Part 2",
    key: 4,
    bpm: 94,
  },
  {
    id: 36,
    artist: "Nas",
    title: "Street Dreams",
    key: 6,
    bpm: 94,
  },
  {
    id: 37,
    artist: "Lil Wayne",
    title: "I Need a Hot Girl",
    key: 6,
    bpm: 94,
  },
  {
    id: 38,
    artist: "Paul Cameron",
    title: "Brown Beat",
    key: 8,
    bpm: 94,
  },
   {
    id: 40,
    artist: "Sean Paul",
    title: "Baby Boy",
    key: 12,
    bpm: 94,
  },
  {
    id: 41,
    artist: "Pastor Troy",
    title: "Are We Cuttin",
    key: 8,
    bpm: 94,
  },
  {
    id: 42,
    artist: "MOP",
    title: "Ante Up",
    key: 4,
    bpm: 94,
  },
  {
    id: 43,
    artist: "Total",
    title: "What About Us Remix",
    key: 3,
    bpm: 94,
  },
  {
    id: 44,
    artist: "Nelly",
    title: "Shake Ya Tailfeather",
    key: 11,
    bpm: 94,
  },
  {
    id: 46,
    artist: "Ludacris",
    title: "Move B*tch",
    key: 11,
    bpm: 94,
  },
  {
    id: 47,
    artist: "Mystikal",
    title: "Been So Long",
    key: 11,
    bpm: 94,
  },
  {
    id: 48,
    artist: "Cheeky Blakk",
    title: "B*tch Get Off Me",
    key: 1,
    bpm: 94,
  },
  {
    id: 49,
    artist: "Chingy",
    title: "Right Thurr",
    key: 2,
    bpm: 94,
  },
  {
    id: 50,
    artist: "Chris Brown",
    title: "Wall 2 Wall",
    key: 4,
    bpm: 94,
  },
  {
    id: 51,
    artist: "Young Buck",
    title: "Shorty Wanna Ride",
    key: 4,
    bpm: 94,
  },
  {
    id: 52,
    artist: "Juvenile",
    title: "In My Life",
    key: 9,
    bpm: 94,
  }, {
    id: 54,
    artist: "Juvenile",
    title: "From Her Mama",
    key: 6,
    bpm: 94,
  },
  {
    id: 55,
    artist: "Big Tymers",
    title: "Number One Stunna",
    key: 1,
    bpm: 94,
  },
  {
    id: 56,
    artist: "Big Tymers",
    title: "Get Your Roll On",
    key: 1,
    bpm: 94,
  },
/*  {
    id: 57,
    artist: "LL Cool J",
    title: "Doin It",
    key: 4,
    bpm: 94,
  },*/
  {
    id: 58,
    artist: "Jim Jones",
    title: "We Fly High",
    key: 1,
    bpm: 94,
  },
  {
    id: 59,
    artist: "Kia Shine",
    title: "Krispy",
    key: 8,
    bpm: 94,
  },
  {
    id: 60,
    artist: "Vockah Redu",
    title: "Roll Call",
    key: 10,
    bpm: 94,
  },
  {
    id: 61,
    artist: "Quint Black",
    title: "Shake Dem Haters Off",
    key: 12,
    bpm: 94,
  },
  {
    id: 62,
    artist: "Traxster",
    title: "Freak Hoes",
    key: 2,
    bpm: 84,
  },
  {
    id: 63,
    artist: "Lil Wayne",
    title: "Bring it Back",
    key: 6,
    bpm: 84,
  },
  {
    id: 64,
    artist: "Youngbloodz",
    title: "Presidential",
    key: 6,
    bpm: 84,
  },
  {
    id: 65,
    artist: "Lil Wayne",
    title: "Go DJ",
    key: 1,
    bpm: 84,
  },
  {
    id: 66,
    artist: "Total",
    title: "What About Us Remix",
    key: 1,
    bpm: 84,
  },
  {
    id: 67,
    artist: "Master P",
    title: "I'm a Ho",
    key: 1,
    bpm: 84,
  },
  {
    id: 68,
    artist: "Jay-Z",
    title: "Dirt Off Your Shoulder",
    key: 3,
    bpm: 84,
  },
  {
    id: 69,
    artist: "Lil Boosie",
    title: "Wipe Me Down Remix",
    key: 4,
    bpm: 84,
  },
  {
    id: 70,
    artist: "Snoop Dogg",
    title: "Woof",
    key: 11,
    bpm: 84,
  },
  {
    id: 72,
    artist: "Kelis",
    title: "Bossy",
    key: 2,
    bpm: 84,
  },
  {
    id: 73,
    artist: "Chris Brown",
    title: "Get Like Me",
    key: 1,
    bpm: 84,
  },
  {
    id: 74,
    artist: "Ludacris",
    title: "Get Back",
    key: 3,
    bpm: 84,
  },
  {
    id: 75,
    artist: "Lil Wayne",
    title: "Stuntin' Like My Daddy",
    key: 11,
    bpm: 84,
  },
  {
    id: 76,
    artist: "Super Duck Breaks",
    title: "Beak This",
    key: 10,
    bpm: 84,
  },
  {
    id: 77,
    artist: "Trillville",
    title: "Some Cut",
    key: 9,
    bpm: 84,
  },
  {
    id: 78,
    artist: "Nelly",
    title: "E.I.",
    key: 1,
    bpm: 84,
  },
  {
    id: 79,
    artist: "504 Boys",
    title: "Wobble Wobble",
    key: 1,
    bpm: 84,
  },
  {
    id: 80,
    artist: "T.I.",
    title: "Big Things Poppin'",
    key: 5,
    bpm: 84,
  },
  {
    id: 81,
    artist: "P$C",
    title: "I'm a King",
    key: 4,
    bpm: 84,
  },
  {
    id: 82,
    artist: "Juvenile",
    title: "Set It Off",
    key: 4,
    bpm: 84,
  },
  {
    id: 83,
    artist: "T.I.",
    title: "24's",
    key: 11,
    bpm: 84,
  },
  {
    id: 84,
    artist: "54th Platoon",
    title: "Holdin' It Down",
    key: 12,
    bpm: 84,
  },
  {
    id: 85,
    artist: "Lil Scrappy",
    title: "No Problem",
    key: 5,
    bpm: 84,
  },
  {
    id: 86,
    artist: "Bubba Sparxxx",
    title: "Ugly",
    key: 11,
    bpm: 94,
  },
  {
    id: 87,
    artist: "Nas",
    title: "Oochie Wally",
    key: 11,
    bpm: 94,
  },
  {
    id: 88,
    artist: "Quint Black",
    title: "Shake Dem Haters Remix",
    key: 12,
    bpm: 94,
  },
  {
    id: 89,
    artist: "Da Sha Ra",
    title: "Bootin' Up",
    key: 1,
    bpm: 94,
  },
  {
    id: 90,
    artist: "Usher",
    title: "You Make Me Wanna Remix",
    key: 5,
    bpm: 84,
  },
  {
    id: 91,
    artist: "Three 6 Mafia",
    title: "You Scared Part 2",
    key: 1,
    bpm: 84,
  },
  {
    id: 92,
    artist: "Nelly",
    title: "Country Grammar",
    key: 6,
    bpm: 84,
  },
  {
    id: 93,
    artist: "Webbie",
    title: "Bad B*tch",
    key: 8,
    bpm: 84,
  },
  {
    id: 94,
    artist: "T.I.",
    title: "Top Back",
    key: 1,
    bpm: 84,
  },
  {
    id: 95,
    artist: "David Banner",
    title: "Shawty Say",
    key: 6,
    bpm: 84,
  },
  {
    id: 96,
    artist: "Lil Keke",
    title: "Southside",
    key: 12,
    bpm: 84,
  },
  {
    id: 97,
    artist: "Kingpin Skinny Pimp",
    title: "TVs Remix",
    key: 9,
    bpm: 84,
  },
  {
    id: 98,
    artist: "Three 6 Mafia",
    title: "Ask & Get It",
    key: 4,
    bpm: 84,
  },
  {
    id: 99,
    artist: "Three 6 Mafia",
    title: "Who Run It",
    key: 6,
    bpm: 84,
  },
/*  {
    id: 100,
    artist: "Jay-Z",
    title: "Hey Papi",
    key: 12,
    bpm: 84,
  },*/
  {
    id: 101,
    artist: "Project Pat",
    title: "Ooh Nuttin",
    key: 2,
    bpm: 84,
  },
  {
    id: 102,
    artist: "Lil Troy",
    title: "We Gon Lean",
    key: 2,
    bpm: 84,
  },
  {
    id: 103,
    artist: "Youngbloodz",
    title: "Datz Me",
    key: 6,
    bpm: 84,
  },
  {
    id: 104,
    artist: "Project Pat",
    title: "Dont Save Her",
    key: 3,
    bpm: 84,
  },
/*  {
    id: 105,
    artist: "E-40",
    title: "Rep Yo City",
    key: 1,
    bpm: 84,
  },*/
  {
    id: 106,
    artist: "Lil Jon",
    title: "I Dont Give a What",
    key: 8,
    bpm: 84,
  },
  {
    id: 107,
    artist: "Rich Boy",
    title: "Throw Some Ds",
    key: 4,
    bpm: 84,
  },
  {
    id: 108,
    artist: "Project Pat",
    title: "Gel and Weave",
    key: 5,
    bpm: 84,
  },
  {
    id: 109,
    artist: "Wacko Skip & Juvenile",
    title: "Nolia Clap",
    key: 2,
    bpm: 84,
  },
  {
    id: 110,
    artist: "Lil Wayne",
    title: "Fireman",
    key: 6,
    bpm: 84,
  },
  {
    id: 111,
    artist: "Yung Joc",
    title: "It's Goin Down",
    key: 1,
    bpm: 84,
  },
  {
    id: 112,
    artist: "Ludacris",
    title: "D@mn",
    key: 9,
    bpm: 84,
  },
  {
    id: 113,
    artist: "Magic",
    title: "I Smoke I Drank Remix",
    key: 9,
    bpm: 84,
  },
  {
    id: 114,
    artist: "DJ KaySlay",
    title: "Who Gives A ...",
    key: 4,
    bpm: 84,
  },
  {
    id: 115,
    artist: "Nelly",
    title: "Air Force Ones",
    key: 10,
    bpm: 84,
  },
  {
    id: 116,
    artist: "Lil Jon",
    title: "Snap Yo Fingers",
    key: 1,
    bpm: 84,
  },
  {
    id: 117,
    artist: "Nelly",
    title: "Grillz",
    key: 11,
    bpm: 84,
  },
  {
    id: 118,
    artist: "Cam'Ron",
    title: "Down and Out",
    bpm: 84,
    key: 4,
  },
  {
    id: 119,
    artist: "Busta Rhymes",
    title: "Break Yo Neck",
    bpm: 84,
    key: 8,
  },
  {
    id: 120,
    artist: "Project Pat",
    title: "Back Clap Remix",
    bpm: 84,
    key: 12,
  },
  {
    id: 121,
    artist: "Three 6 Mafia",
    title: "Ridin Spinners",
    bpm: 84,
    key: 8,
  },
  {
    id: 122,
    artist: "Ludacris",
    title: "D@mn Remix",
    key: 9,
    bpm: 84,
  },
  {
    id: 123,
    artist: "Too Short",
    title: "Shake That Monkey",
    key: 8,
    bpm: 102,
  },
  {
    id: 124,
    artist: "Juelz Santana",
    title: "There It Go",
    bpm: 102,
    key: 6,
  },
  {
    id: 125,
    artist: "LL Cool J",
    title: "Headsprung",
    bpm: 102,
    key: 1,
  },
/*  {
    id: 126,
    artist: "Sean Paul",
    title: "Get Busy",
    bpm: 102,
    key: 2,
  },*/
  {
    id: 127,
    artist: "Choppa",
    title: "Choppa Style",
    key: 2,
    bpm: 102,
  },
  {
    id: 128,
    artist: "Master P",
    title: "Rock It",
    bpm: 102,
    key: 1,
  },
  {
    id: 129,
    artist: "Too Short",
    title: "Blow the Whistle",
    bpm: 102,
    key: 5,
  },
  {
    id: 130,
    artist: "Too Short",
    title: "Burn Rubber",
    bpm: 102,
    key: 5,
  },
  {
    id: 131,
    artist: "Lil Jon",
    title: "Get Low",
    key: 5,
    bpm: 102,
  },
  {
    id: 132,
    artist: "Master P",
    title: "Them Jeans",
    key: 5,
    bpm: 102,
  },
  {
    id: 133,
    artist: "Da Sha Ra",
    title: "Bootin' Up",
    key: 2,
    bpm: 102,
  },
  {
    id: 134,
    artist: "Loon",
    title: "How U Want That",
    key: 1,
    bpm: 102,
  },
  {
    id: 135,
    artist: "Khia",
    title: "My Neck, My Back",
    key: 8,
    bpm: 102,
  },
  {
    id: 136,
    artist: "Ying Yang Twins",
    title: "Salt Shaker",
    key: 2,
    bpm: 102,
  },
  {
    id: 137,
    artist: "Usher",
    title: "Yeah",
    bpm: 102,
    key: 6,
  },
  {
    id: 138,
    artist: "T.I.",
    title: "I'm Serious Remix",
    bpm: 102,
    key: 9,
  },
  {
    id: 139,
    artist: "Busta Rhymes",
    title: "Light Your A$$ On Fire",
    bpm: 102,
    key: 12,
  },
  {
    id: 140,
    artist: "Missy Elliott",
    title: "Work It",
    key: 5,
    bpm: 102,
  },
  {
    id: 141,
    artist: "E-40",
    title: "Tell Me When To Go",
    bpm: 102,
    key: 9,
  },
  {
    id: 142,
    artist: "The Showboys",
    title: "Drag Rap",
    bpm: 94,
    key: 9,
  },
  {
    id: 143,
    artist: "Young Gunz",
    title: "Can't Stop Won't Stop",
    key: 1,
    bpm: 102,
  },
  {
    id: 144,
    artist: "Petey Pablo",
    title: "Freek a Leek",
    bpm: 102,
    key: 1,
  },
  {
    id: 145,
    artist: "Ludacris",
    title: "Stand Up",
    bpm: 102,
    key: 3,
  },
  {
    id: 146,
    artist: "Cheeky Blakk",
    title: "B*tch Get Off Me",
    bpm: 102,
    key: 1,
  },
  {
    id: 147,
    artist: "Jay-Z",
    title: "Just Wanna Luv U",
    bpm: 102,
    linkageId: 1,
    key: 4,
  },
  {
    id: 148,
    artist: "Silky Slim",
    title: "Sista Sista",
    bpm: 102,
    key: 6,
  },
  {
    id: 149,
    artist: "Ludacris",
    title: "Area Codes",
    bpm: 102,
    key: 8,
  },
  {
    id: 150,
    artist: "Chris Brown",
    title: "Run It",
    key: 2,
    bpm: 102,
  },
  {
    id: 151,
    artist: "Ying Yang Twins",
    title: "Whistle While You Twerk",
    bpm: 102,
    key: 2,
  },
  {
    id: 152,
    artist: "5th Ward Webbie",
    title: "On Da Wall",
    bpm: 102,
    key: 11,
  },
  {
    id: 153,
    artist: "5th Ward Webbie",
    title: "Toot It Up",
    bpm: 102,
    key: 6,
  },
  {
    id: 154,
    artist: "The Pack",
    title: "Vans",
    bpm: 102,
    key: 2,
  },
  {
    id: 155,
    artist: "Montell Jordan",
    title: "This Is How We Do It",
    bpm: 102,
    key: 4,
  },
  {
    id: 156,
    artist: "Ying Yang Twins",
    title: "Whisper",
    key: 3,
    bpm: 102,
  },
  {
    id: 157,
    artist: "FRESH",
    title: "Cake Boy",
    bpm: 84,
    key: 2,
  },
  {
    id: 158,
    artist: "Bloodclot Breaks",
    title: "Kuttin Like a Maniac",
    bpm: 84,
    key: 2,
  },
  {
    id: 159,
    artist: "Super Seal",
    title: "Side B Break",
    bpm: 84,
    key: 8,
  },
  {
    id: 160,
    artist: "Fat Joe",
    title: "Make It Rain",
    bpm: 84,
    key: 11,
  },
  {
    id: 161,
    artist: "Crime Mobb",
    title: "Rock Ya Hips",
    bpm: 84,
    key: 1,
  },
  {
    id: 162,
    artist: "Crime Mobb",
    title: "Stilettos",
    bpm: 84,
    key: 1,
  },
  {
    id: 163,
    artist: "DJ DMD",
    title: "25 Lighters",
    key: 2,
    bpm: 84,
  },
  {
    id: 164,
    artist: "Ludacris",
    title: "Catch Up",
    bpm: 84,
    key: 11,
  },
  {
    id: 165,
    artist: "8-Ball & MJG",
    title: "Pimp Hard",
    bpm: 84,
    key: 12,
  },
  {
    id: 166,
    artist: "Three 6 Mafia",
    title: "Chickenheads",
    bpm: 84,
    key: 1,
  },
  {
    id: 167,
    artist: "Bravehearts",
    title: "Quick to Back Down",
    bpm: 84,
    key: 4,
  },
  {
    id: 168,
    artist: "G-Unit",
    title: "Wanna Get to Know You",
    key: 5,
    bpm: 84,
  },
  {
    id: 169,
    artist: "Gangsta Boo",
    title: "Where Dem Dollas At",
    bpm: 84,
    key: 2,
  },
  {
    id: 170,
    artist: "Tango",
    title: "Wobble & Shake It",
    bpm: 84,
    key: 9,
  },
 {
    id: 172,
    artist: "Webbie",
    title: "How U Ridin'",
    key: 6,
    bpm: 84,
  },
  {
    id: 173,
    artist: "Jim Jones",
    title: "Weatherman",
    bpm: 84,
    key: 3,
  },
  {
    id: 174,
    artist: "Ludacris",
    title: "Act a Fool",
    key: 9,
    bpm: 84,
  },
  {
    id: 175,
    artist: "Mobb Deep",
    title: "Get It Twisted",
    key: 1,
    bpm: 102,
  },
  {
    id: 176,
    artist: "Saweetie",
    title: "My Type Remix",
    key: 6,
    bpm: 102,
  },
  {
    id: 177,
    artist: "Ying Yang Twins",
    title: "Get It Girl",
    key: 1,
    bpm: 102,
  },
  {
    id: 178,
    artist: "Big Freedia",
    title: "A$$ Everywhere",
    key: 4,
    bpm: 102,
  },
  {
    id: 179,
    artist: "Drake",
    title: "Nice for What",
    key: 4,
    bpm: 94,
  },
  {
    id: 180,
    artist: "Joe Budden",
    title: "Pump It Up",
    key: 3,
    bpm: 102,
  },
  {
    id: 181,
    artist: "DJ Felli Fell",
    title: "Get Buck in Here",
    bpm: 102,
    key: 1,
  },
  {
    id: 182,
    artist: "B.G.",
    title: "Bling Bling",
    bpm: 102,
    key: 9,
  },
  {
    id: 185,
    artist: "Busta Rhymes",
    title: "Fire It Up",
    key: 8,
    bpm: 102,
  },
  {
    id: 186,
    artist: "Too Short",
    title: "Keep Bouncing",
    bpm: 102,
    key: 10,
  },
  {
    id: 187,
    artist: "Notorious BIG",
    title: "Nasty Girl",
    bpm: 102,
    key: 12,
  },
  {
    id: 188,
    artist: "Saweetie",
    title: "Up Now",
    bpm: 102,
    key: 2,
  },
  {
    id: 189,
    artist: "Missy Elliott",
    title: "Ching a Ling",
    key: 4,
    bpm: 102,
  },
  {
    id: 190,
    artist: "Kilo",
    title: "Who Dat Call tha Police",
    key: 1,
    bpm: 102,
  },
  {
    id: 191,
    artist: "Kilo",
    title: "Get In Line",
    key: 3,
    bpm: 102,
  },
  {
    id: 192,
    artist: "Mobb Deep",
    title: "Real Gangstaz",
    key: 9,
    bpm: 102,
  },
  {
    id: 193,
    artist: "Doug E Fresh",
    title: "The Show",
    key: 4,
    bpm: 102,
  },
  {
    id: 194,
    artist: "50 Cent",
    title: "Candy Shop",
    bpm: 102,
    key: 6,
  },
   {
    id: 200,
    artist: "FM",
    title: "Gimme What You Got",
    bpm: 102,
    key: 2,
  },
  {
    id: 207,
    artist: "Master P",
    title: "Ghetto D",
    key: 5,
    bpm: 102,
  },
  {
    id: 208,
    artist: "Mystikal",
    title: "Shake Ya Ass",
    key: 1,
    bpm: 102,
  },
  {
    id: 209,
    artist: "Naughty by Nature",
    title: "O.P.P.",
    bpm: 102,
    key: 6,
  },
  /*{
    id: 210,
    artist: "Onyx",
    title: "Slam",
    bpm: 102,
    key: 3,
  },*/
   {
    id: 213,
    artist: "R Kelly",
    title: "Playas Only",
    key: 1,
    bpm: 102,
  },
   {
    id: 216,
    artist: "Skee Lo",
    title: "I Wish",
    bpm: 102,
    key: 1,
  },
  {
    id: 217,
    artist: "Swizz Beats",
    title: "Money In the Bank",
    bpm: 102,
    key: 2,
  },
  {
    id: 218,
    artist: "The Game",
    title: "How We Do",
    bpm: 102,
    key: 4,
  },
  {
    id: 224,
    artist: "The Game",
    title: "Hate It or Love It",
    bpm: 102,
    key: 12,
  },
  {
    id: 227,
    artist: "Ying Yang Twins",
    title: "Twurkulator Part 2",
    key: 7,
    bpm: 102,
  },
  {
    id: 230,
    artist: "Next",
    title: "Too Close",
    key: 11,
    bpm: 102,
  },
  /*{
    id: 236,
    artist: "Ying Yang Twins",
    title: "Twerking in the Mirror",
    bpm: 102,
    key: 2,
  },*/
   {
    id: 242,
    artist: "Beyonce",
    title: "Naughty Girl",
    key: 10,
    bpm: 102,
  },
  {
    id: 243,
    artist: "Slim",
    title: "So Fly Remix",
    key: 7,
    bpm: 94,
  },
   {
    id: 260,
    artist: "Amerie",
    title: "1 Thing",
    key: 5,
    bpm: 102,
  },
  {
    id: 263,
    artist: "Youngbloodz",
    title: "Cadillac Pimpin",
    bpm: 94,
    key: 2,
  },
  /*{
    id: 270,
    artist: "Junior MAFIA",
    title: "Get Money",
    bpm: 94,
    key: 5,
  },*/
  {
    id: 273,
    artist: "Rihanna feat Young Jeezy",
    title: "Hard",
    bpm: 94,
    key: 5,
  },
  /*{
    id: 275,
    artist: "Eve",
    title: "Tamborine Remix",
    key: 5,
    bpm: 102,
  },
  {
    id: 276,
    artist: "Funkdoobiest",
    title: "Bow Wow Wow Remix",
    bpm: 102,
    key: 11,
  },*/
   {
    id: 278,
    artist: "Bhad Barbie",
    title: "Bestie",
    key: 4,
    bpm: 102,
  },
   {
    id: 280,
    artist: "DMX",
    title: "Stop Bein Greedy",
    key: 5,
    bpm: 102,
  },
   {
    id: 283,
    artist: "Baby",
    title: "Do That",
    key: 1,
    bpm: 102,
  },
  {
    id: 284,
    artist: "Hot Boys",
    title: "I Got That Fire",
    key: 4,
    bpm: 102,
  },
  {
    id: 285,
    artist: "Juelz Santana",
    title: "Hey Ma",
    bpm: 84,
    key: 6,
  },
  {
    id: 286,
    artist: "Hurricane Chris",
    title: "Hand Clap",
    bpm: 84,
    key: 11,
  },
  {
    id: 287,
    artist: "Eightball",
    title: "Lay It Down",
    key: 4,
    bpm: 84,
  },
  {
    id: 289,
    artist: "Outkast",
    title: "So Fresh So Clean",
    key: 5,
    bpm: 84,
  },
  {
    id: 290,
    artist: "MoneyBagg Yo",
    title: "Wockesha Remix",
    key: 8,
    bpm: 84,
  },
  {
    id: 291,
    artist: "Master P",
    title: "Make Em Say Uhhh",
    key: 4,
    bpm: 84,
  },
  {
    id: 292,
    artist: "Funk Shid Up",
    title: "Sucka Stepped Up",
    bpm: 84,
    key: 6,
  },
  {
    id: 294,
    artist: "Missy Elliott",
    title: "Hot Boyz",
    bpm: 84,
    key: 11,
  },
   {
    id: 296,
    artist: "T-Pain",
    title: "Got Money",
    bpm: 84,
    key: 9,
  },
  {
    id: 298,
    artist: "Audio Two",
    title: "Top Billin",
    key: 4,
    bpm: 94,
  },
  {
    id: 299,
    artist: "50 Cent",
    title: "Get Up",
    key: 10,
    bpm: 94,
  },
   {
    id: 301,
    artist: "City Girls",
    title: "P&ssy Talk",
    key: 1,
    bpm: 102,
  },
   {
    id: 303,
    artist: "Cam'Ron",
    title: "Oh Boy",
    bpm: 84,
    key: 1,
  },
  {
    id: 304,
    artist: "T.I.",
    title: "Front Back",
    key: 2,
    bpm: 84,
  },
   /*{
    id: 306,
    artist: "Lord Tariq & Peter Gunz",
    title: "Deva Vu Uptown Baby",
    key: 7,
    bpm: 102,
  },*/
  {
    id: 307,
    artist: "NORE",
    title: "Nothin",
    key: 8,
    bpm: 102,
  },
  {
    id: 308,
    artist: "Paperboy",
    title: "Ditty",
    key: 7,
    bpm: 102,
  },
  /*{
    id: 309,
    artist: "The Game",
    title: "Game's Pain",
    key: 6,
    bpm: 102,
  },*/
  {
    id: 310,
    artist: "DMX",
    title: "Up In Here",
    key: 2,
    bpm: 102,
  },
  {
    id: 311,
    artist: "Outkast",
    title: "Rosa Parks",
    key: 1,
    bpm: 102,
  },
  {
    id: 312,
    artist: "Baby D",
    title: "F That Side",
    key: 2,
    bpm: 102,
  },
  {
    id: 313,
    artist: "Lil Goldie",
    title: "Act a Donkey",
    key: 12,
    bpm: 102,
  },
  {
    id: 314,
    artist: "5th Ward Webbie",
    title: "Toot it Up Remix",
    key: 6,
    bpm: 102,
  },
  {
    id: 316,
    artist: "Jay-Z",
    title: "Excuse Me Miss Remix",
    key: 4,
    bpm: 102,
  },
  {
    id: 317,
    artist: "Tracey Lee",
    title: "The Theme",
    key: 1,
    bpm: 102,
  },
  {
    id: 318,
    artist: "Pras",
    title: "Ghetto Superstar",
    key: 4,
    bpm: 102,
  },
  {
    id: 319,
    artist: "Lauryn Hill",
    title: "That Thing",
    key: 2,
    bpm: 102,
  },
  {
    id: 320,
    artist: "Notorious BIG",
    title: "Goin Back to Cali",
    key: 3,
    bpm: 102,
  },
  {
    id: 321,
    artist: "DJ Khaled",
    title: "Holla At Me",
    key: 4,
    bpm: 102,
  },
  {
    id: 322,
    artist: "Megan thee Stallion",
    title: "Hot Girl Summer",
    key: 3,
    bpm: 102,
  },
  {
    id: 323,
    artist: "G-Unit",
    title: "Ryder Part 2",
    key: 4,
    bpm: 102,
  },
  {
    id: 324,
    artist: "Murphy Lee",
    title: "What the Hook Gon Be",
    key: 4,
    bpm: 102,
  },
/*  {
    id: 325,
    artist: "Puff Daddy",
    title: "Can't Hold Me Down",
    key: 4,
    bpm: 102,
  },*/
  /*{
    id: 326,
    artist: "DJ Jazzy Jeff",
    title: "Brand New Funk",
    key: 4,
    bpm: 102,
  },*/
   {
    id: 329,
    artist: "Fat Joe",
    title: "Lean Back Remix",
    key: 8,
    bpm: 102,
  },
 /* {
    id: 330,
    artist: "Wyclef Jean",
    title: "We Trying to Stay Alive",
    key: 4,
    bpm: 102,
  },*/
  {
    id: 331,
    artist: "G Dep",
    title: "Special Delivery",
    key: 2,
    bpm: 102,
  },
  {
    id: 332,
    artist: "Offset & Metro Boomin",
    title: "Ric Flair Drip",
    key: 2,
    bpm: 102,
  },
  {
    id: 333,
    artist: "Bubba Sparxx",
    title: "Ms New Booty",
    key: 1,
    bpm: 102,
  },
  {
    id: 334,
    artist: "E-40",
    title: "White Girl",
    key: 2,
    bpm: 102,
  },
  /*{
    id: 335,
    artist: "Notorious BIG",
    title: "Dead Wrong",
    key: 1,
    bpm: 84,
  },*/
  {
    id: 336,
    artist: "DJ UNK",
    title: "Walk It Out",
    key: 9,
    bpm: 84,
  },
  {
    id: 337,
    artist: "Lil Boosie",
    title: "Supafly",
    key: 11,
    bpm: 84,
  },
  {
    id: 338,
    artist: "Jamie Foxx",
    title: "Blame It",
    key: 3,
    bpm: 84,
  },
  {
    id: 339,
    artist: "Gucci Mane",
    title: "Go Head",
    key: 1,
    bpm: 84,
  },
  {
    id: 340,
    artist: "Durrough",
    title: "Walk that Walk",
    key: 9,
    bpm: 84,
  },
  {
    id: 343,
    artist: "Bun B",
    title: "That's Gangsta",
    key: 9,
    bpm: 84,
  },
  {
    id: 344,
    artist: "Cookie Ekawaii",
    title: "If I Back It Up",
    key: 1,
    bpm: 84,
  },
  {
    id: 346,
    artist: "Young Jeezy",
    title: "Get Some Money",
    key: 2,
    bpm: 84,
  },
  {
    id: 347,
    artist: "Lil Boosie",
    title: "Zoom",
    key: 4,
    bpm: 84,
  },
  {
    id: 348,
    artist: "MIMS",
    title: "This is Why I'm Hot",
    key: 12,
    bpm: 84,
  },
  /*{
    id: 349,
    artist: "Nappy Roots",
    title: "Aww-Naww",
    key: 1,
    bpm: 84,
  },*/
  {
    id: 350,
    artist: "Webbie",
    title: "Like That",
    key: 12,
    bpm: 84,
  },
  {
    id: 351,
    artist: "Young Jeezy",
    title: "Black Tee",
    key: 6,
    bpm: 84,
  },
  {
    id: 352,
    artist: "UGK",
    title: "Let Me See It",
    key: 4,
    bpm: 84,
  },
  {
    id: 354,
    artist: "Webbie",
    title: "Gimme That",
    key: 1,
    bpm: 84,
  },
  {
    id: 355,
    artist: "Lil Boosie",
    title: "Adios",
    key: 11,
    bpm: 84,
  },
  {
    id: 356,
    artist: "Gucci Mane",
    title: "Wasted",
    key: 2,
    bpm: 84,
  },
  {
    id: 357,
    artist: "D4L",
    title: "Laffy Taffy",
    key: 1,
    bpm: 84,
  },
  {
    id: 358,
    artist: "T.I.",
    title: "Rubber Band Man",
    key: 1,
    bpm: 84,
  },
  /*{
    id: 359,
    artist: "Rocko",
    title: "Tomorrow",
    key: 6,
    bpm: 84,
  },
  {
    id: 360,
    artist: "Concrete Boys",
    title: "Crank Dat Roadrunner",
    key: 2,
    bpm: 84,
  },*/
  /*{
    id: 361,
    artist: "Project Pat",
    title: "Good Googly Moogly",
    key: 1,
    bpm: 84,
  },*/
  {
    id: 362,
    artist: "T.I.",
    title: "Be Easy",
    key: 4,
    bpm: 84,
  },
  {
    id: 363,
    artist: "DJ UNK",
    title: "2 Step",
    key: 1,
    bpm: 84,
  },
  {
    id: 364,
    artist: "Petey Pablo",
    title: "Raise Up",
    key: 2,
    bpm: 84,
  },
  {
    id: 365,
    artist: "Gz",
    title: "Do the Stanky Leg",
    key: 5,
    bpm: 84,
  },
   {
    id: 367,
    artist: "Cali Swag District",
    title: "Teach Me How to Dougie",
    key: 10,
    bpm: 84,
  },
  {
    id: 368,
    artist: "Trillville",
    title: "Neva Eva",
    key: 2,
    bpm: 84,
  },
  {
    id: 370,
    artist: "Kilo",
    title: "Tick Tock Bass Remix",
    key: 1,
    bpm: 84,
  },
  /*{
    id: 372,
    artist: "Eminem",
    title: "Stan",
    key: 6,
    bpm: 84,
  },*/
  /*{
    id: 373,
    artist: "Billy Wes",
    title: "Shake That Jelly",
    key: 2,
    bpm: 84,
  },*/
  /*{
    id: 375,
    artist: "The Game",
    title: "Big Dreams",
    key: 1,
    bpm: 84,
  },*/
  {
    id: 376,
    artist: "T.I.",
    title: "ASAP",
    key: 2,
    bpm: 84,
  },
  {
    id: 377,
    artist: "TELA",
    title: "Got Pimpin",
    key: 10,
    bpm: 84,
  },
  {
    id: 378,
    artist: "Shawty Lo",
    title: "Supplier",
    key: 9,
    bpm: 84,
  },
  /*{
    id: 382,
    artist: "Juvenile",
    title: "Rodeo",
    key: 11,
    bpm: 84,
  },*/
  {
    id: 383,
    artist: "JR Writer",
    title: "Grill Em",
    key: 11,
    bpm: 84,
  },
  {
    id: 388,
    artist: "Yo Gotti",
    title: "King Sh*t",
    key: 4,
    bpm: 84,
  },
  {
    id: 390,
    artist: "ASAP",
    title: "Rocky Cocky",
    key: 2,
    bpm: 84,
  },
  {
    id: 391,
    artist: "Yung LA",
    title: "Ain't I",
    key: 4,
    bpm: 84,
  },
 /* {
    id: 392,
    artist: "Youngbloodz",
    title: "85",
    key: 4,
    bpm: 84,
  },
   {
    id: 396,
    artist: "The Game",
    title: "Put You In the Game",
    key: 6,
    bpm: 84,
  },*/
   {
    id: 398,
    artist: "Pitbull",
    title: "Dem Miami Boys",
    key: 2,
    bpm: 84,
  },
  {
    id: 400,
    artist: "Notorious BIG",
    title: "Big Poppa",
    key: 8,
    bpm: 84,
  },
  {
    id: 401,
    artist: "Youngbloodz",
    title: "Presidential Remix",
    key: 1,
    bpm: 84,
  },
  {
    id: 402,
    artist: "T.I.",
    title: "You Know What It Is",
    key: 9,
    bpm: 84,
  },
  {
    id: 403,
    artist: "Kingpin Skinny Pimp",
    title: "TVs",
    key: 9,
    bpm: 84,
  },
  {
    id: 404,
    artist: "Black Rob",
    title: "Whoa",
    key: 11,
    bpm: 84,
  },
  {
    id: 406,
    artist: "Beastie Boys",
    title: "Posse In Effect",
    key: 1,
    bpm: 84,
  },
  {
    id: 407,
    artist: "Three 6 Mafia",
    title: "Side 2 Side",
    key: 10,
    bpm: 84,
  },
  {
    id: 408,
    artist: "Mystikal",
    title: "Here I Go",
    key: 3,
    bpm: 84,
  },
   {
    id: 410,
    artist: "Luniz",
    title: "I Got 5 On It",
    key: 4,
    bpm: 84,
  },
  {
    id: 411,
    artist: "Dogg Pound",
    title: "New York New York",
    key: 11,
    bpm: 84,
  },
   {
    id: 414,
    artist: "Lil Wayne",
    title: "The Block is Hot",
    key: 2,
    bpm: 84,
  },
  {
    id: 416,
    artist: "Cassidy",
    title: "Drink & My 2 Step",
    key: 8,
    bpm: 84,
  },
  {
    id: 417,
    artist: "Paul Wall",
    title: "Bizzy Body",
    key: 2,
    bpm: 84,
  },
  {
    id: 418,
    artist: "Webbie",
    title: "Independent",
    key: 2,
    bpm: 84,
  },
  {
    id: 419,
    artist: "Field Mob",
    title: "Sick of Being Lonely",
    key: 1,
    bpm: 84,
  },
  /*{
    id: 420,
    artist: "Above the Law",
    title: "Black Superman",
    key: 8,
    bpm: 84,
  },*/
  {
    id: 421,
    artist: "Ron Browz",
    title: "Jumpin Out the Window",
    key: 1,
    bpm: 84,
  },
  {
    id: 422,
    artist: "DJ Khaled",
    title: "Out Here Grinding",
    key: 5,
    bpm: 84,
  },
  {
    id: 423,
    artist: "Big Tymers",
    title: "Big Ballin",
    key: 12,
    bpm: 84,
  },
  {
    id: 425,
    artist: "Birdman",
    title: "What Happened to That Boy",
    key: 10,
    bpm: 94,
  },
  {
    id: 426,
    artist: "Snoop Dogg",
    title: "Drop It Like Its Hot Remix",
    key: 5,
    bpm: 94,
  },
  {
    id: 427,
    artist: "Nelly",
    title: "E.I. Tipdrill Remix",
    key: 2,
    bpm: 94,
  },
 /* {
    id: 428,
    artist: "Junior MAFIA",
    title: "Players Anthem Remix",
    key: 11,
    bpm: 94,
  },*/
   {
    id: 431,
    artist: "T.I.",
    title: "Get Loose",
    key: 2,
    bpm: 94,
  },
  {
    id: 432,
    artist: "Jermaine Dupri",
    title: "Welcome to Atlanta ATL Remix",
    key: 1,
    bpm: 94,
  },
  {
    id: 435,
    artist: "Megan thee Stallion",
    title: "Girls In The Hood",
    key: 11,
    bpm: 94,
  },
  {
    id: 436,
    artist: "Mike Jones",
    title: "Drop & Gimme 50",
    key: 9,
    bpm: 94,
  },
  {
    id: 437,
    artist: "Durrough",
    title: "Ice Cream Paint Job",
    key: 12,
    bpm: 94,
  },
  {
    id: 438,
    artist: "Rihanna",
    title: "Birthday Cake Remix",
    key: 2,
    bpm: 84,
  },
  {
    id: 439,
    artist: "Future",
    title: "Stick Talk",
    key: 7,
    bpm: 84,
  },
  {
    id: 440,
    artist: "Drake",
    title: "First Person Shooter",
    key: 9,
    bpm: 84,
  },
  {
    id: 441,
    artist: "Master P",
    title: "Weed & Money",
    key: 2,
    bpm: 84,
  },
  {
    id: 442,
    artist: "Drake",
    title: "Rich Flex",
    key: 8,
    bpm: 84,
  },
  {
    id: 443,
    artist: "Playboi Carti",
    title: "Milli Rock",
    key: 10,
    bpm: 84,
  },
  {
    id: 444,
    artist: "Three 6 Mafia",
    title: "Hard Out Here",
    key: 9,
    bpm: 84,
  },
  {
    id: 445,
    artist: "Gunna",
    title: "Pushin P",
    key: 1,
    bpm: 84,
  },
  {
    id: 446,
    artist: "Travis Scott & Drake",
    title: "SICKO MODE",
    key: 3,
    bpm: 84,
  },
  {
    id: 447,
    artist: "Whodini",
    title: "I'm a Ho",
    key: 1,
    bpm: 84,
  },
  {
    id: 448,
    artist: "Drake",
    title: "Girls Want Girls",
    key: 5,
    bpm: 84,
  },
  {
    id: 449,
    artist: "2 Chainz & Lil Wayne",
    title: "Big Diamonds",
    key: 3,
    bpm: 84,
  },
  {
    id: 450,
    artist: "Three 6 Mafia",
    title: "Let's Run a Train",
    key: 2,
    bpm: 84,
  },
  {
    id: 451,
    artist: "Drake",
    title: "No Friends in the Industry",
    key: 2,
    bpm: 84,
  },
  {
    id: 452,
    artist: "Future",
    title: "I Serve the Base",
    key: 8,
    bpm: 84,
  },
  {
    id: 453,
    artist: "Future",
    title: "Freak Hoe",
    key: 12,
    bpm: 84,
  },
  {
    id: 454,
    artist: "Cardi B",
    title: "Up",
    key: 9,
    bpm: 84,
  },
  {
    id: 455,
    artist: "Future",
    title: "For a Nut",
    key: 5,
    bpm: 84,
  },
  {
    id: 456,
    artist: "Megan thee Stallion",
    title: "Captain Hook",
    key: 6,
    bpm: 84,
  },
  {
    id: 457,
    artist: "SR3MM",
    title: "T'd Up",
    key: 5,
    bpm: 84,
  },
  {
    id: 458,
    artist: "Drake",
    title: "Nonstop",
    key: 11,
    bpm: 84,
  },
  {
    id: 459,
    artist: "Future",
    title: "I'm on One",
    key: 2,
    bpm: 84,
  },
  {
    id: 460,
    artist: "Drake",
    title: "Gods Plan",
    key: 1,
    bpm: 84,
  },
  {
    id: 461,
    artist: "Li Uzi Vert",
    title: "XO TOUR LIFE",
    key: 1,
    bpm: 84,
  },
  {
    id: 462,
    artist: "Mr Bigg",
    title: "Hos",
    key: 7,
    bpm: 84,
  },
  {
    id: 463,
    artist: "Dem Franchize Boys",
    title: "I Think They Like Me",
    key: 5,
    bpm: 84,
  },
  {
    id: 464,
    artist: "Sexy Redd",
    title: "Pound Town",
    key: 1,
    bpm: 94,
  },
/*  {
    id: 465,
    artist: "Ghostface600",
    title: "Pray to the East",
    key: 9,
    bpm: 94,
  },*/
  {
    id: 468,
    artist: "Rick Ross & Meek Mill",
    title: "Lyrical Eazy",
    key: 5,
    bpm: 94,
  },
  {
    id: 469,
    artist: "Gucci Mane",
    title: "There I Go",
    key: 12,
    bpm: 94,
  },
  /*{
    id: 474,
    artist: "Too Short",
    title: "Young Thang",
    key: 4,
    bpm: 94,
  },*/
  {
    id: 476,
    artist: "2rare",
    title: "Lil Mama",
    key: 1,
    bpm: 94,
  },
  /*{
    id: 478,
    artist: "The Game",
    title: "Violence",
    key: 8,
    bpm: 94,
  },*/
  {
    id: 485,
    artist: "10 KANs",
    title: "D In Your Life",
    key: 9,
    bpm: 102,
  },
  /*{
    id: 486,
    artist: "2Pac",
    title: "Still Ballin",
    key: 2,
    bpm: 102,
  },*/
  {
    id: 487,
    artist: "Das EFX",
    title: "They Want EFX",
    key: 1,
    bpm: 102,
  },
  /*{
    id: 488,
    artist: "Kurupt",
    title: "We Can Freak It",
    key: 12,
    bpm: 102,
  },*/
  {
    id: 489,
    artist: "Wale",
    title: "Chillin",
    key: 1,
    bpm: 102,
  },
 /*{
    id: 492,
    artist: "Derek B",
    title: "Good Groove",
    key: 5,
    bpm: 102,
  },*/
  {
    id: 493,
    artist: "50 Cent",
    title: "Disco Inferno",
    key: 1,
    bpm: 102,
  },
  /*{
    id: 496,
    artist: "LL Cool J",
    title: "Eat Em Up L Chill Remix",
    key: 1,
    bpm: 102,
  },*/
  {
    id: 497,
    artist: "Fabolous",
    title: "Baby Don't Go",
    key: 1,
    bpm: 102,
  },
  /*{
    id: 498,
    artist: "Diggy feat French Montana",
    title: "Ain't Bout to Do",
    key: 11,
    bpm: 102,
  },*/
  {
    id: 499,
    artist: "DJ Khaled Lil Baby & Future",
    title: "SUPPOSED TO BE LOVED",
    key: 1,
    bpm: 102,
  },
  {
    id: 500,
    artist: "Pusha T",
    title: "Let the Smokers Shine the Coupes",
    key: 5,
    bpm: 102,
  },
  {
    id: 511,
    artist: "Blueface",
    title: "Thotiana",
    key: 1,
    bpm: 102,
  },
  {
    id: 512,
    artist: "Black Sheep",
    title: "The Choice is Yours",
    key: 3,
    bpm: 102,
  },
  /*{
    id: 513,
    artist: "Shakira",
    title: "Hips Don't Lie",
    key: 3,
    bpm: 102,
  },*/
  {
    id: 514,
    artist: "Beastie Boys",
    title: "AWOL",
    key: 1,
    bpm: 102,
  },
  {
    id: 515,
    artist: "Ray J",
    title: "Wait a Minute",
    key: 1,
    bpm: 102,
  },
  /*{
    id: 516,
    artist: "Frankie Cutlass",
    title: "Puerto Rico",
    key: 10,
    bpm: 102,
  },*/
  {
    id: 517,
    artist: "T.I.",
    title: "Bring Em Out",
    key: 9,
    bpm: 102,
  },
  /*{
    id: 520,
    artist: "Notorious BIG",
    title: "Mo Money Mo Problems",
    key: 1,
    bpm: 102,
  },*/
  /*{
    id: 521,
    artist: "Showbiz & AG",
    title: "Party Groove",
    key: 10,
    bpm: 102,
  },*/
  {
    id: 522,
    artist: "Mario",
    title: "Boom Remix",
    key: 1,
    bpm: 102,
  },
  {
    id: 523,
    artist: "Positive K",
    title: "I Got a Man",
    key: 5,
    bpm: 102,
  },
  {
    id: 524,
    artist: "Busta Rhymes",
    title: "What It Is",
    key: 4,
    bpm: 102,
  },
  {
    id: 526,
    artist: "Kilo",
    title: "Get In Line 2",
    key: 3,
    bpm: 102,
  },
    {
        id: 577,
        artist: "IamSu & Lil Jon",
        title: "Yay Area",
        key: 7,
        bpm: 102,
    },
    /*{
        id: 578,
        artist: "Mischif",
        title: "Drink In My Hand",
        key: 7,
        bpm: 102,
    },
    {
        id: 579,
        artist: "Aitch & Tracey R",
        title: "Kid",
        key: 7,
        bpm: 102,
    },
    {
        id: 580,
        artist: "Pretty Emage & DJ Rapture",
        title: "Walk Thru",
        key: 2,
        bpm: 102,
    },
    {
        id: 581,
        artist: "Godlands",
        title: "Middleman",
        key: 1,
        bpm: 102,
    },
    {
        id: 582,
        artist: "Fuego the Profit",
        title: "My Guy",
        key: 1,
        bpm: 102,
    },*/
    /*{
        id: 583,
        artist: "DJ Five Venoms ft Cliff Savage & Moe",
        title: "Replay",
        key: 1,
        bpm: 102,
    },*/
    {
        id: 584,
        artist: "Black Sheep",
        title: "The Choice is Yours",
        key: 3,
        bpm: 102,
    },
   /* {
        id: 585,
        artist: "69 Boys & Ying Yang Twins",
        title: "Grown Zone",
        key: 1,
        bpm: 102,
    },*/
    {
        id: 586,
        artist: "Ying Yang Twins",
        title: "Wait Remix",
        key: 3,
        bpm: 102,
    },
    {
        id: 587,
        artist: "Wale feat J. Cole",
        title: "Poke It Out",
        key: 1,
        bpm: 102,
    },
    /*{
        id: 588,
        artist: "Tash",
        title: "Rap Life",
        key: 8,
        bpm: 102,
    },
    {
        id: 589,
        artist: "Marc Nasty",
        title: "Thick B*tch",
        key: 12,
        bpm: 102,
    },
    {
        id: 590,
        artist: "Lola Brooke feat Billy B",
        title: "Don't Play With It",
        key: 10,
        bpm: 102,
    },*/
    {
        id: 591,
        artist: "Lil Jon & Mac Dre",
        title: "Ain't No Tellin",
        key: 1,
        bpm: 102,
    },
    /*{
        id: 592,
        artist: "Kalan FrFr feat Tyga",
        title: "Butterfly Coupe",
        key: 11,
        bpm: 102,
    },*/
    /*{
        id: 593,
        artist: "K.Comedy, Key Glock & Mac",
        title: "Sauce",
        key: 2,
        bpm: 102,
    },*/
    {
        id: 594,
        artist: "Juvenile",
        title: "Understand",
        key: 5,
        bpm: 102,
    },
    /*{
        id: 595,
        artist: "Juice Froot",
        title: "Christmas List",
        key: 6,
        bpm: 102,
    },*/
    /*{
        id: 596,
        artist: "Guapdad 4000",
        title: "Cheap",
        key: 2,
        bpm: 102,
    },
    {
        id: 597,
        artist: "Rotimi",
        title: "In My Bed",
        key: 6,
        bpm: 102,
    },*/
    {
        id: 598,
        artist: "London Juve",
        title: "Throw a Fit",
        key: 2,
        bpm: 102,
    },
    /*{
        id: 599,
        artist: "Young Pooda",
        title: "Repeat",
        key: 10,
        bpm: 102,
    },*/
    {
        id: 600,
        artist: "Ying Yang Twins",
        title: "Get It Girl",
        key: 1,
        bpm: 102,
    },
    /*{
        id: 601,
        artist: "Ultramagnetic MCs",
        title: "Ease Back",
        key: 2,
        bpm: 102,
    },*/
    {
        id: 602,
        artist: "Lil Kim",
        title: "I'll Be",
        key: 2,
        bpm: 102,
    },
    {
        id: 604,
        artist: "50 Cent",
        title: "Get Gully",
        key: 8,
        bpm: 94,
    },
    {
        id: 605,
        artist: "50 Cent",
        title: "Baby By Me",
        key: 5,
        bpm: 94,
    },
    {
        id: 606,
        artist: "2Pac",
        title: "California Love",
        key: 1,
        bpm: 94,
    },
    /*{
        id: 607,
        artist: "2 Chainz",
        title: "Million Dollars With of Game",
        key: 8,
        bpm: 94,
    },*/
    /*{
        id: 608,
        artist: "Yung Lott, Larry June & Big Guce",
        title: "Thuggin",
        key: 12,
        bpm: 94,
    },*/
    /*{
        id: 609,
        artist: "Young Boy Never Broke Again",
        title: "Don't Rate Me",
        key: 12,
        bpm: 94,
    },*/
    /*{
        id: 610,
        artist: "Young Roddy",
        title: "Weed & Women",
        key: 3,
        bpm: 94,
    },*/
    {
        id: 611,
        artist: "Yella Beezy",
        title: "Talk My Sh*t",
        key: 3,
        bpm: 94,
    },
    {
        id: 614,
        artist: "Soulja Boy",
        title: "Donk",
        key: 1,
        bpm: 94,
    },
    {
        id: 615,
        artist: "Saweetie",
        title: "Emotional",
        key: 1,
        bpm: 94,
    },
/*    {
        id: 619,
        artist: "NLE Choppa",
        title: "Glide With Me",
        key: 9,
        bpm: 94,
    },*/
    {
        id: 620,
        artist: "Nicki Minaj",
        title: "Ruby Da Sleaze",
        key: 7,
        bpm: 94,
    },
    /*{
        id: 621,
        artist: "Lola Brooke",
        title: "Dummy Ummy",
        key: 11,
        bpm: 94,
    },*/
    /*{
        id: 622,
        artist: "Nightcrawlers",
        title: "Push the Feeling On",
        key: 11,
        bpm: 123,
    },
    {
        id: 623,
        artist: "Petra",
        title: "Just Let Go",
        key: 5,
        bpm: 123,
    },
    {
        id: 624,
        artist: "Steve Pointdexter",
        title: "Computer Madness",
        key: 12,
        bpm: 123,
    },
    {
        id: 625,
        artist: "Royal Orchestra",
        title: "Mykoos Melodee",
        key: 10,
        bpm: 123,
    },
    {
        id: 626,
        artist: "KDubb",
        title: "Get Busy Huh What",
        key: 10,
        bpm: 123,
    },
    {
        id: 627,
        artist: "KC Flight",
        title: "Voices Dub",
        key: 10,
        bpm: 123,
    },
    {
        id: 628,
        artist: "Karizma",
        title: "Jumpin",
        key: 2,
        bpm: 123,
    },
    {
        id: 629,
        artist: "Mr. Fingers",
        title: "Can You Feel It",
        key: 8,
        bpm: 123,
    },
    {
        id: 630,
        artist: "Cajmere & Dajae",
        title: "Brighter Days Todd's TNT Dub",
        key: 8,
        bpm: 123,
    },
    {
        id: 631,
        artist: "Barbara Tucker",
        title: "I Get Lifted Go to Church Mix",
        key: 7,
        bpm: 123,
    },
    {
        id: 632,
        artist: "Deskee",
        title: "Let There Be House",
        key: 5,
        bpm: 123,
    },
    {
        id: 633,
        artist: "Those Guys",
        title: "Can You Feel It",
        key: 4,
        bpm: 123,
    },
    {
        id: 634,
        artist: "Cajmere",
        title: "Percolator",
        key: 4,
        bpm: 123,
    },
    {
        id: 635,
        artist: "Tru 2 Lyfe",
        title: "Go",
        key: 2,
        bpm: 123,
    },
    {
        id: 636,
        artist: "Real McCoy",
        title: "Another Night",
        key: 2,
        bpm: 123,
    },*/
    {
        id: 637,
        artist: "DJ Khaled",
        title: "POPSTAR",
        key: 5,
        bpm: 84,
    },
    {
        id: 638,
        artist: "Future",
        title: "Like That",
        key: 11,
        bpm: 84,
    },
    {
        id: 639,
        artist: "BIA & Nicki Minaj",
        title: "WHOLE LOTTA MONEY Remix",
        key: 1,
        bpm: 84,
    },
    {
        id: 640,
        artist: "Nardo Wick",
        title: "Me or Sum",
        key: 1,
        bpm: 84,
    },
    {
        id: 641,
        artist: "G Herbo",
        title: "Who Run It",
        key: 11,
        bpm: 84,
    },
    {
        id: 642,
        artist: "DaBaby",
        title: "NASTY",
        key: 6,
        bpm: 84,
    },
    {
        id: 644,
        artist: "Gunna",
        title: "too easy",
        key: 4,
        bpm: 84,
    },
    {
        id: 645,
        artist: "Project Pat",
        title: "North Memphis",
        key: 11,
        bpm: 84,
    },
    {
        id: 646,
        artist: "Project Pat",
        title: "Break the Law 2001",
        key: 6,
        bpm: 84,
    },
    {
        id: 647,
        artist: "Meek Mill",
        title: "Sharing Locations",
        key: 2,
        bpm: 84,
    },
    {
        id: 648,
        artist: "Meek Mill",
        title: "Hot",
        key: 7,
        bpm: 84,
    },
    {
        id: 649,
        artist: "JiD",
        title: "Surround Sound",
        key: 4,
        bpm: 84,
    },
    {
        id: 650,
        artist: "Travis Scott",
        title: "Highest in the Room Remix",
        key: 1,
        bpm: 84,
    },
    {
        id: 651,
        artist: "21 Savage",
        title: "Redrum",
        key: 7,
        bpm: 84,
    },
    {
        id: 652,
        artist: "A$AP Ferg",
        title: "Plain Jane",
        key: 2,
        bpm: 84,
    },
    {
        id: 653,
        artist: "Southside",
        title: "Blue Jean Bandit",
        key: 1,
        bpm: 84,
    },
    {
        id: 654,
        artist: "Sexy Red",
        title: "Skee Ye",
        key: 4,
        bpm: 84,
    },
    {
        id: 655,
        artist: "Drake",
        title: "Family Matters",
        key: 4,
        bpm: 84,
    },
    {
        id: 656,
        artist: "Don Toliver",
        title: "After Party",
        key: 7,
        bpm: 84,
    },
    {
        id: 657,
        artist: "YG",
        title: "Go Loko",
        key: 10,
        bpm: 102,
    },
    {
        id: 658,
        artist: "Kendrick Lamar",
        title: "Not Like Us",
        key: 10,
        bpm: 102,
    },
/*    {
        id: 659,
        artist: "Young Gunz",
        title: "Can't Stop Won't Stop Remix",
        key: 1,
        bpm: 102,
    },*/
    {
        id: 660,
        artist: "Mustard & Migos",
        title: "Pure Water",
        key: 5,
        bpm: 102,
    },
    {
        id: 661,
        artist: "Kanye West & Ty Dolla Sign",
        title: "Do It",
        key: 2,
        bpm: 102,
    },
    {
        id: 662,
        artist: "Lil Jon",
        title: "Turn Down for What",
        key: 9,
        bpm: 102,
    },
];
